# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/flyme/Documents/Course/Vivado/Arch/arch-fa23/src/lab5/Exp5_NEXYS_A7/Exp6.srcs/sources_1/ip/multiplier/multiplier.xci
# IP: The module: 'multiplier' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/flyme/Documents/Course/Vivado/Arch/arch-fa23/src/lab5/Exp5_NEXYS_A7/Exp6.gen/sources_1/ip/multiplier/multiplier_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'multiplier'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/flyme/Documents/Course/Vivado/Arch/arch-fa23/src/lab5/Exp5_NEXYS_A7/Exp6.srcs/sources_1/ip/multiplier/multiplier.xci
# IP: The module: 'multiplier' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/flyme/Documents/Course/Vivado/Arch/arch-fa23/src/lab5/Exp5_NEXYS_A7/Exp6.gen/sources_1/ip/multiplier/multiplier_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'multiplier'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
